/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author prado
 */
public class ClienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClienteGUI
     */
    public ClienteGUI() {
        initComponents();
        hacerInterfaz();
    }
    
     public void hacerInterfaz ()
    {
        this.setTitle("Cliente");
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.areaChat.setEditable(false);
    }
     
    public void actualizarChat(String msj)
    {
        this.areaChat.append("Servidor dice: "+msj+"\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor_areaChat = new javax.swing.JPanel();
        Scroll = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        contenedor_btntxt = new javax.swing.JPanel();
        txt_mensaje = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaChat.setColumns(20);
        areaChat.setRows(5);
        Scroll.setViewportView(areaChat);

        javax.swing.GroupLayout contenedor_areaChatLayout = new javax.swing.GroupLayout(contenedor_areaChat);
        contenedor_areaChat.setLayout(contenedor_areaChatLayout);
        contenedor_areaChatLayout.setHorizontalGroup(
            contenedor_areaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll)
        );
        contenedor_areaChatLayout.setVerticalGroup(
            contenedor_areaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        txt_mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mensajeActionPerformed(evt);
            }
        });

        btn_enviar.setText("Enviar");

        javax.swing.GroupLayout contenedor_btntxtLayout = new javax.swing.GroupLayout(contenedor_btntxt);
        contenedor_btntxt.setLayout(contenedor_btntxtLayout);
        contenedor_btntxtLayout.setHorizontalGroup(
            contenedor_btntxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_btntxtLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_enviar)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        contenedor_btntxtLayout.setVerticalGroup(
            contenedor_btntxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_btntxtLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(contenedor_btntxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enviar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor_areaChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(contenedor_btntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor_areaChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contenedor_btntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mensajeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JTextArea areaChat;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JPanel contenedor_areaChat;
    private javax.swing.JPanel contenedor_btntxt;
    private javax.swing.JTextField txt_mensaje;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getScroll() {
        return Scroll;
    }

    public JTextArea getAreaChat() {
        return areaChat;
    }

    public JButton getBtn_enviar() {
        return btn_enviar;
    }

    public JPanel getContenedor_areaChat() {
        return contenedor_areaChat;
    }

    public JPanel getContenedor_btntxt() {
        return contenedor_btntxt;
    }

    public JTextField getTxt_mensaje() {
        return txt_mensaje;
    }

    
}
